spring.application.name=automation
spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=gpt-4o-mini

# PostgreSQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/placement_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:0000}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Notion Integration Configuration
notion.api.token=${NOTION_API_TOKEN:}
notion.api.database.id=${NOTION_DATABASE_ID:}

# WhatsApp API Configuration
whatsapp.api.token=${WHATSAPP_API_TOKEN:}
whatsapp.api.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID:}

